# Generated by Django 2.2.8 on 2020-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
