# Generated by Django 2.2.8 on 2020-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200214_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(default='img/bg-img/48.jpg', upload_to='images/user'),
        ),
    ]
