# Generated by Django 2.2.8 on 2020-02-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200214_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(default='media_cdn/image/article/pexels-photo-1082958.jpeg', upload_to='images/user'),
        ),
    ]
