# Generated by Django 2.2.8 on 2020-02-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200214_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(default='image/article/pexels-photo-1082958.jpeg', upload_to='images/user'),
        ),
    ]
